version: '3'

services:
  web:
    image: nginx:latest
    depends_on:
      - composer
    ports:
      - "80:80"
    volumes:
      - ./src:/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7-fpm
    depends_on:
      - composer
    volumes:
      - ./src:/www

  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
      - .:/app